version: "2.0"

services:
  web:
    build: ./nginx
    ports: 
      - 8001:80
    volumes:
      - ${PWD}/nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ${PWD}/nginx/www:/www
    command: /usr/local/nginx/sbin/nginx -g 'daemon off;'
  php:
    build: ./php
    ports:
      - 9000:9000
    volumes:
      - ${PWD}/php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ${PWD}/php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ${PWD}/nginx/www:/www
    command: /usr/local/php/sbin/php-fpm -c /usr/local/php/etc/php-fpm.conf
